require "json"

task "fate" do
  TaskHelpers.fate.run
end

task "test" => %w[ fate ] do
  sh "coffee test/functional/base.coffee"
end


module TaskHelpers
  require "fate"
  require "fate/repl"

  def self.fate
    @fate ||= begin
      configuration = JSON.parse(
        File.read("test/fate.json"),
        :symbolize_names => true
      )

      fate = Fate.new configuration,
        :output => {
          "default" => Fate::Output::IOMux.new( :file => "test/fate.log" ),
        }
      fate.control
    end

  end

end
